### ISSUE TITLE
FTPD not playing nice with Hekate bootprotect

### ISSUE THREAD

**Issue by ToxiClay** [mtheall/ftpd#146] opened 2022-03-31 15:18 UTC
**Describe the bug**
Enabling the bootprotect setting within `hekate_ipl.ini` causes FTPD and, potentially, all similar homebrew to throw a 550 I/O error and die during the directory retrieval stage due to blocking reading within HOS.

**To Reproduce**
Attempt to establish an FTP connection.

**Expected behavior**
I expected the FTP connection to construct normally.

**Screenshots**
![QwV9Rwl](https://user-images.githubusercontent.com/13796683/161072147-17c14bc0-d209-47ec-91f1-160d52e84372.jpg)
![QDz39dM](https://user-images.githubusercontent.com/13796683/161072478-3b408a54-3982-42cd-828e-34730534e1b1.png)

**Platform (please complete the following information):**
- Nintendo Switch
- HOS 13.2.1|AMS1.2.6
- HBMenu
- NRO

**Additional context**
CTCaer says this is your problem to fix as the FTPD developer.

**Comment by mtheall** [comment] 2022-03-31 15:40
Duplicate of #139

**Closed by mtheall** 2022-03-31 15:40 UTC
